### PR TITLE
Fix set nil value

### LINKED ISSUE #96: nil value not set
A `nil` value in the input should set a pointer in the destination struct to nil. 

Example program:
```
package main

import (
	"fmt"
	mstruct "github.com/mitchellh/mapstructure"
)

type T struct {
	A *int
}

func main() {
	x := 5
	dest := &T{A: &x}

	valueMap := map[string]interface{}{
		"A": nil,
	}

	conf := &mstruct.DecoderConfig{
		ErrorUnused:      false,
		WeaklyTypedInput: false,
		Metadata:         nil,
		Result:           dest,
		ZeroFields:       true,
	}
	dec, err := mstruct.NewDecoder(conf)
	if err != nil {
		panic(err.Error())
	}
	err = dec.Decode(valueMap)
	if err != nil {
		panic(err.Error())
	}

	fmt.Printf("%#v\n", dest.A)
}
```

Prints: `(*int)(0xc42000e2d8)` not `(*int)(nil)`. T.A is not modified.

### PR DESCRIPTION
**Pull request by calvn**
Sorry for hijacking #90. I merged from master to fix the conflicts, and added the tests as suggested by @mitchellh.

Closes #96
Closes #90

### CODE REVIEW

File: mapstructure.go [hunk 1]
```diff
@@ -225,7 +225,15 @@ func (d *Decoder) Decode(input interface{}) error {
 // Decodes an unknown data type into a specific reflection value.
 func (d *Decoder) decode(name string, input interface{}, outVal reflect.Value) error {
 	if input == nil {
-		// If the input is nil, then we don't set anything.
+		// If the data is nil, then we don't set anything, unless ZeroFields is set
+		// to true.
+		if d.config.ZeroFields {
+			outVal.Set(reflect.Zero(outVal.Type()))
+
+			if d.config.Metadata != nil && name != "" {
```
Comment (calvn) [inline mapstructure.go]: I am wondering if we should do the same thing in https://github.com/mitchellh/mapstructure/pull/109/files#diff-80aa7a137566e62ca9976c661b2b1a65R244 as well since we we are technically using the key and setting it to its zero value.

**Comment by calvn** [comment]
I added metadata value checks on the tests. Let me know if this is not the desired behavior and I'll revert.
