### PR TITLE
decodeMapFromStruct: Only deref element if we're squashing the struct

### LINKED ISSUE #231: 1.4.0: decode hooks receive the wrong type for the `to` argument
I attempted to upgrade from mapstructure 1.3.3 to 1.4.0 in Consul and a few of the test failed.

Debugging one of the tests it seems to be that the decode hook (`reflect.Type` hook) is receiving `map[string]interface {}` as the type of the  `to` argument, where as previously it received `time.Time` as the type of `to`.

Test failures can be seen here: https://app.circleci.com/pipelines/github/hashicorp/consul/15588/workflows/76c7848b-f780-4049-aa5c-f091b737207b/jobs/302146

I suspect the change which added a new `reflect.Value` version of hooks may have broken this. I'll keep looking to see if I can find a fix.

More details:
1. squash is not being used
2. the decode is struct->struct
3. this particular hook is checking the type of both `from` and `to`
3. previously the decode hook would be called twice, now the decode hook is being called 4 times
4. previously it was the second call which receives a from and to of the correct types, now the second call receives the right type for the `from`, and the forth call receives the correct type for `to`. In both cases the other type is `map[string]interface {}`, even though neither the input or output contain a map.

I suspect it is not actually the change to hooks that broke this. It seems like it was one of the changes to `decodeStructFromMap`.

### PR DESCRIPTION
**Pull request by mitchellh**
Fixes #231

This also reverts the test _change_ that was introduced in 231 back to
the original test. This retains the _new tests_ added in 231 to verify
the behavior of 231.

cc @dnephin

### CODE REVIEW

File: mapstructure_test.go [hunk 1]
```diff
@@ -2390,26 +2390,7 @@ func TestDecode_StructTaggedWithOmitempty_KeepNonEmptyValues(t *testing.T) {
...
-				"VjsonFloat":  float64(0),
-				"VjsonInt":    0,
-				"VjsonNumber": json.Number(""),
-				"VjsonUint":   uint(0),
-				"Vstring":     "",
-				"Vuint":       uint(0),
-			},
-			"Vfoo": "",
-		},
+		"omittable-nested": &Nested{},
```
Comment (mitchellh) [inline mapstructure_test.go:2393]: This is just reverting the change in #205 back to what the test originally was.

**Review by dnephin — APPROVED** [review]
Nice! LGTM, thank you for fixing! 

I'll give it another try with Consul test suite tomorrow, but I'm pretty sure this will fix it.

**Comment by dnephin** [comment]
Confirmed the tests are now passing with this change: https://app.circleci.com/pipelines/github/hashicorp/consul/15897/workflows/c753022b-01e0-4e03-8b95-2fdd980be546/jobs/308971
